#goal definition
geometry_msgs/PoseStamped[] poses
fognav_msgs/Task[] tasks
string behavior_tree
bool not_auto_land
bool loop_tasks # If true, after all complete, it will start from the first again by marking all as not started
bool abort_on_failure
int16 wait_secs_for_next_goal # If 0, no wait. <=-1, wait indefinetely. >0, wait for the specified number of seconds
bool reset_previous_state # If true, the backlog inside the navigator will be reset, abort the ongoing task if exists, then start from beginning
---
#result definition
std_msgs/Empty result
fognav_msgs/TaskMetaData[] tasks_metadata_result
---
geometry_msgs/PoseStamped current_pose
builtin_interfaces/Duration navigation_time
builtin_interfaces/Duration estimated_time_remaining
int16 number_of_recoveries
float32 distance_remaining
int16 number_of_poses_remaining
fognav_msgs/TaskMetaData[] tasks_metadata_feedback
